import { Trip } from './supabase'

export const mockTrips: Trip[] = [
  {
    id: '550e8400-e29b-41d4-a716-446655440001',
    created_at: new Date().toISOString(),
    name: 'Dunas do Jalapão',
    description: 'Explore as imponentes dunas douradas do Jalapão, um dos maiores desertos interiores da América do Sul. Uma experiência única no coração do Brasil.',
    location: 'Parque Estadual do Jalapão, TO',
    duration_days: 5,
    price: 2890,
    max_spots: 12,
    available_spots: 5,
    departure_date: '2025-07-15',
    return_date: '2025-07-20',
    image_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    highlights: ['Dunas de areia branca', 'Pôr do sol espetacular', 'Banho nas dunas', 'Acampamento no deserto'],
    includes: ['Transporte 4x4', 'Guia especializado', 'Alimentação completa', 'Equipamento de camping', 'Seguro viagem'],
    is_active: true,
    itinerary: [],
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440002',
    created_at: new Date().toISOString(),
    name: 'Fervedouros Encantados',
    description: 'Mergulhe nos fervedouros — nascentes de água cristalina onde a pressão da água cria o efeito de "ferver" sem calor. Um fenômeno natural inexplicável.',
    location: 'Mateiros, TO',
    duration_days: 4,
    price: 2290,
    max_spots: 10,
    available_spots: 3,
    departure_date: '2025-08-05',
    return_date: '2025-08-09',
    image_url: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800',
    highlights: ['Fervedouro do Buritizinho', 'Fervedouro da Fumaça', 'Cachoeira da Velha', 'Rio Novo'],
    includes: ['Transporte 4x4', 'Guia local certificado', 'Hospedagem em pousada', 'Café da manhã regional', 'Seguro viagem'],
    is_active: true,
    itinerary: [],
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440003',
    created_at: new Date().toISOString(),
    name: 'Expedição Completa Jalapão',
    description: 'A experiência definitiva do Jalapão. 7 dias percorrendo as principais atrações: dunas, fervedouros, cânions e o cerrado mais intocado do planeta.',
    location: 'Jalapão — Tocantins, TO',
    duration_days: 7,
    price: 4590,
    max_spots: 8,
    available_spots: 2,
    departure_date: '2025-07-28',
    return_date: '2025-08-04',
    image_url: 'https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=800',
    highlights: ['Dunas do Jalapão', 'Serra do Espírito Santo', 'Cachoeira da Velha', 'Travessia completa do parque', 'Artesanato em capim dourado'],
    includes: ['Transporte 4x4 exclusivo', 'Guia especialista', 'Alimentação completa', 'Hospedagem mista (pousada + camping)', 'Kit capim dourado', 'Seguro premium'],
    is_active: true,
    itinerary: [],
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440004',
    created_at: new Date().toISOString(),
    name: 'Capim Dourado & Cultura Tocantinense',
    description: 'Descubra o artesanato único do Capim Dourado, patrimônio cultural do Tocantins. Visite comunidades tradicionais e leve para casa uma peça exclusiva.',
    location: 'São Félix do Tocantins, TO',
    duration_days: 3,
    price: 1590,
    max_spots: 15,
    available_spots: 8,
    departure_date: '2025-09-12',
    return_date: '2025-09-15',
    image_url: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800',
    highlights: ['Oficina de capim dourado', 'Visita a comunidades quilombolas', 'Culinária regional', 'Fervedouros próximos'],
    includes: ['Transporte', 'Guia cultural', 'Hospedagem em pousada', 'Alimentação completa', 'Peça artesanal inclusa'],
    is_active: true,
  },
]
